-- Migración aditiva. No borra filas, columnas ni datos existentes.
-- Ejecutar en el SQL Editor de Supabase.

alter table public.clinical_histories
  add column if not exists patient_address text not null default '',
  add column if not exists patient_city text not null default '',
  add column if not exists patient_gender text not null default '',
  add column if not exists consultation_time text not null default '',
  add column if not exists personal_history text not null default '',
  add column if not exists family_history text not null default '',
  add column if not exists surgical_history text not null default '',
  add column if not exists pharmacological_history text not null default '',
  add column if not exists allergic_history text not null default '',
  add column if not exists gynecological_obstetric_history text not null default '',
  add column if not exists blood_pressure text not null default '',
  add column if not exists heart_rate text not null default '',
  add column if not exists respiratory_rate text not null default '',
  add column if not exists temperature text not null default '',
  add column if not exists oxygen_saturation text not null default '',
  add column if not exists weight text not null default '',
  add column if not exists height text not null default '',
  add column if not exists bmi text not null default '',
  add column if not exists general_appearance text not null default '',
  add column if not exists head_and_neck text not null default '',
  add column if not exists cardiovascular_exam text not null default '',
  add column if not exists respiratory_exam text not null default '',
  add column if not exists abdominal_exam text not null default '',
  add column if not exists neurological_exam text not null default '',
  add column if not exists musculoskeletal_exam text not null default '',
  add column if not exists other_physical_findings text not null default '',
  add column if not exists secondary_diagnoses text not null default '',
  add column if not exists clinical_impression text not null default '',
  add column if not exists medical_recommendations text not null default '',
  add column if not exists requested_exams text not null default '',
  add column if not exists referrals text not null default '',
  add column if not exists follow_up text not null default '';
